mqtt:
  broker: 192.168.1.134 # localhost
  port: 1883
  QOS: 1

camera:
  video_source: 0
  fps: 2  
  mqtt_topic: homie/mac_webcam/capture

processing:
  subscribe_topic: homie/mac_webcam/capture
  publish_topic: homie/mac_webcam/capture/rotated

save-captures:
  mqtt_topic: homie/mac_webcam/capture
  captures_directory: captures/